name: math_question
description: A new Flutter project.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  dio: ^4.0.0
  mock_web_server: ^4.1.1
  get_it: ^7.2.0
  injectable: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  injectable_generator: ^1.5.2
  build_runner: ^2.1.4

flutter:
  uses-material-design: true
  assets:
    - assets/json/
